### ISSUE TITLE
toString Using forEach() & stream() API

### ISSUE THREAD

**Issue by Andzura** [PolytechLyon/4a-isi3-tp1-2016-2017-groupe-2-baud-jeune#2]
@Slashgear j'ai essayé de faire le toString en utilisant les spécificités de Java 8 pour les collections :  
```java
StringBuilder sb = new StringBuilder();
sb.append("Graph \n");
this.getAllNodes().forEach(n ->{
        sb.append("[Node=");
        sb.append(n).append(" : [");
        sb.append(this.getArc(n).parallelStream()
                .map(Arc::toString)
                .collect(Collectors.joining(" , ")));
        sb.append("]]\n");
    } );
return sb.toString();
 ```
et je me suis demandé si ça avait un impact sur la performance, et si oui à quel point.
j'ai testé sur des très gros Graph (ie 1000k nodes) et je remarque que cette version est plus coûteuse (principalement en temps, il me semble que c'était équivalent au niveau mémoire) que la version "normale" qui utilise une boucle foreach.
Je me demande donc si c'est l'utilisation des Stream qui n'est pas utile pour ce problème, ou si je l'ai juste mal utilisé.

**Comment by Slashgear** [comment]
L'ouverture d'un stream() ou d'un parallelStream() prend du temps.
Mais sur de grand nombres l'api stream doit être plus efficace.

L'appel au paralleleStream() est peut être un peu too much ici

Ton graph a N noeuds et M arcs.
Si en moyenne tu as peu d'arc par noeuds dans ton graph, l'ouverture du parralleleStream sur la liste des arc du noeuds est peut-être too much.

N'hésites pas à faire un peu de profilling pour voir quelle méthode est couteuse.
(Tu as plein de plugin IntelliJ pour faire du profiling)

**Comment by Slashgear** [comment]
J'ai retrouvé un article bien fait sur les bench entre l'utilisation des stream et l'utilisation des for 

https://blog.codefx.org/java/stream-performance/ 

🎁
